from __future__ import annotations

import logging
from pathlib import Path
from typing import Iterable

from raster_tilemaker.config import (
    DEFAULT_FORMAT,
    DEFAULT_QUALITY,
    DEFAULT_TILE_SIZE,
    TILE_CONFIG_NAME,
)
from raster_tilemaker.output.pmtiles import write_pmtiles_archive, write_pmtiles_archive_parallel
from raster_tilemaker.render.mosaic import (
    iter_rendered_mosaic_tiles,
    render_mosaic_tiles,
    read_vrt_metadata,
)
from raster_tilemaker.tile_config import build_tile_config, write_tile_config

logger = logging.getLogger(__name__)


def build_mosaic_output(
    input_vrt: Path,
    output_root: Path,
    resolutions: Iterable[float],
    *,
    tile_size: int = DEFAULT_TILE_SIZE,
    quality: int = DEFAULT_QUALITY,
    tile_format: str = DEFAULT_FORMAT,
    output_kind: str = "zxy",
    pmtiles_file: Path = Path("tiles.pmtiles"),
    render_workers: int | None = None,
) -> dict:
    resolutions_list = list(resolutions)

    logger.info(
        "Reading VRT metadata",
        extra={"vrt_path": str(input_vrt)},
    )
    source = read_vrt_metadata(input_vrt)
    aggregate_bounds_crs = source.bounds
    min_x, _, _, max_y = aggregate_bounds_crs
    origin = (min_x, max_y)
    logger.info(
        "VRT metadata loaded",
        extra={
            "band_count": source.band_count,
            "bounds_crs": list(aggregate_bounds_crs),
            "origin": list(origin),
        },
    )

    config = build_tile_config(
        source.crs_wkt,
        aggregate_bounds_crs,
        resolutions_list,
        origin,
        tile_size=tile_size,
        tile_format=tile_format,
    )
    config_name = (
        f"{pmtiles_file.stem}-config.json" if output_kind == "pmtiles" else TILE_CONFIG_NAME
    )
    config_path = write_tile_config(output_root, config, file_name=config_name)
    logger.info("Tile config written", extra={"config_path": str(config_path)})

    logger.info("Beginning tile render", extra={"output_kind": output_kind})

    if output_kind == "zxy":
        render_mosaic_tiles(
            input_vrt,
            output_root,
            tile_size=tile_size,
            quality=quality,
            tile_format=tile_format,
            aggregate_bounds=aggregate_bounds_crs,
            origin=origin,
            resolutions=resolutions_list,
        )
        return config

    if output_kind != "pmtiles":
        raise ValueError(f"Unsupported output kind: {output_kind}")

    pmtiles_path = pmtiles_file if pmtiles_file.is_absolute() else output_root / pmtiles_file
    shared_metadata = {
        "name": "raster-tilemaker output",
        "description": "Generated by flyer-maps raster-tilemaker.",
        "type": "overlay",
        "format": tile_format,
    }

    if render_workers == 1:
        rendered_tiles = iter_rendered_mosaic_tiles(
            input_vrt,
            tile_size=tile_size,
            aggregate_bounds=aggregate_bounds_crs,
            origin=origin,
            resolutions=resolutions_list,
        )
        write_pmtiles_archive(
            rendered_tiles,
            pmtiles_path,
            tile_format=tile_format,
            quality=quality,
            resolutions=resolutions_list,
            bounds_wgs84=tuple(config["extent"]["wgs84"]),
            metadata=shared_metadata,
        )
    else:
        write_pmtiles_archive_parallel(
            input_vrt,
            pmtiles_path,
            tile_format=tile_format,
            quality=quality,
            resolutions=resolutions_list,
            bounds_wgs84=tuple(config["extent"]["wgs84"]),
            aggregate_bounds=aggregate_bounds_crs,
            origin=origin,
            band_count=source.band_count,
            tile_size=tile_size,
            metadata=shared_metadata,
            render_workers=render_workers,
        )
    return config
